### ISSUE TITLE
How to fit blockmodels on a fix (given) number of cluster?

### ISSUE THREAD

**Issue by jchiquet** [jchiquet/missSBM#13]
This will save time in the tests, I only manage to fit on "up to" a required number of clusters :+1: 

```r
BM <- blockmodels::BM_bernoulli_covariates("SBM_sym", A, covariates_BM, verbosity = 0, explore_max = Q, plotting = "", ncores = 1)
```

**Comment by Demiperimetre** [comment]
J'ai l'impression que blockmodel part forcément de 1 cluster et que explore_min le force à aller au moins jusqu'à un certain nombre de cluster. 
Sinon pour information l'autre paramètre utile pour l'exploration est exploration_factor qui permet de fixer le nombre max de cluster exploré en fonction du maximum trouvé. C'est à dire le nombre de clusters qu'il va aller explorer après avoir observé la descente d'ICL.

**Comment by jchiquet** [comment]
Ok donc pas possible.
