### ISSUE TITLE
Find a small network data set to illustrate the package

### ISSUE THREAD

**Issue by jchiquet** [jchiquet/missSBM#18]
This can be as simple as the karate club network with some randomnly sampled edges and dyad.

**Comment by Demiperimetre** [comment]
J'ai trouvé ça dans un papier que j'ai reviewé. L'intérêt est qu'il y a une classification naturelle utilisable à laquelle on peut se comparer.

American political view books network 105 nœuds, 441 liens, 2 blocs a priori en communauté
https://wiki.cs.umd.edu/cmsc734_09/index.php?title=Social_Network_of_Political_Books

American College Football game 115 nœuds, 613 liens, 12 blocs a prior en communauté
http://www.seldomusedreserve.com/?page_id=8805

French political blog network 196 nœuds, 2864 liens en 10 blocs a priori en communauté
https://rdrr.io/cran/sand/man/fblog.html

Network of English words in David Copperfield (de Dickens pas le magicien...) 112 nœuds en 532 liens en a priori 2 blocs en bipartite
http://konect.uni-koblenz.de/networks/adjnoun_adjacency

Eu research institute email network 1005 nœuds, 25571 liens en a priori 42 blocs en communauté
https://snap.stanford.edu/data/email-Eu-core.html

Des foods webs dirigés 
http://cosinproject.eu/extra/data/foodwebs/WEB.html

**Comment by jchiquet** [comment]
@Demiperimetre Parfait, tu peux extraire les fichiers rdata correspondant et les mettre par exemple au format igraph ?

**Comment by Demiperimetre** [comment]
will do

**Comment by jchiquet** [comment]
@Demiperimetre  glad to know. Looking forward to it.

**Comment by Demiperimetre** [comment]
new branch with data created: networksExamples, Dude.

**Comment by jchiquet** [comment]
En plus d'utiliser un petit réseau (genre French blogosphere, mais qui data de 13 ans tout de même), je pense qu'on pourrait trouver un réseau un peu plus sexy avec des données plus récentes en allant jeter un coup d'oeil appuyé du côté de https://www.data.gouv.fr

Si on envisage un papier dans JSS, ça serait la moindre des choses.

Qu'en dites-vous ?

**Comment by jchiquet** [comment]
Par ailleurs, si on utilise la French blogosphere, autant récupérer les données la description faites dans feu le package mixer.
