### ISSUE TITLE
Initial imputation in missSBM-fit is probably not adapted to cases with covariates

### ISSUE THREAD

**Issue by jchiquet** [jchiquet/missSBM#22]
Maybe related to #21, the following code for first estimation of pi in missSBM-fit is relevant for problem without covariates (when private$pi is indeed the mathematical matrix of connectivity between blocks)

https://github.com/jchiquet/missSBM/blob/18c3959d60ae4cf12039e37492987e89a8702253/R/missingSBM_fit.R#L32-L37

However, when private$pi represent gamma, as it is the case for the model with covariatess, we should adapt this first initialization and imputation. It has been show to be crucial in order to reproduce properly the resuts found with @TabouyT 's implementation. 

So @TabouyT , comment initialises-tu les pi/gamma dans le modèles avec covariables ?

**Comment by TabouyT** [comment]
Je fais comme dans le SBM sans covariables, je mets des 0 à la place des NA, et j'utilise la classification initiale du spectral clustering pour calculer l'estimateur de pi. Puis, je dis que gamma c'est le logit de pi.

**Comment by jchiquet** [comment]
J'ai trouver un truc dégueux qui semble fonctionner (au moins aussi bien que ton code). On en reste là pour l'instant...
