### ISSUE TITLE
Bug: Forward smoothing

### ISSUE THREAD

**Issue by TabouyT** [jchiquet/missSBM#24]
Recurrent Error : "Error: number of cluster centres must lie between 1 and nrow(x)".
Probably due to K-means algorithm when splitting a class into two when only one node is in the class.
Solution : prevent these cases with a "if"

**Comment by Demiperimetre** [comment]
j'ai un bug sur ma vignette quand j'essaie d'ajuster le SBM sur la matrice totalemetn observée. J'ai l'impression que c'est le même problème que celui évoqué par Timothée. Tous les ICL calculés sont à NaN

**Comment by TabouyT** [comment]
Ça marche sur les données totalement observées chez moi ...

**Comment by jchiquet** [comment]
Je suis en train de travailler sur le smoothing : je développe un objet missSBMcollection dont le smoothing serait une méthode.

Quand vous avez un bug, pour faciliter la résolution, il faut inclure un bout de code qui permette de le reproduire, sinon c'est sans espoir.

**Comment by jchiquet** [comment]
Le bug dans la vignette de @Demiperimetre est corrigé. Celui que mentionne @TabouyT  doit venir d'ailleurs mais j'ai besoin d'un example reproductible, comme d'hab.

**Comment by TabouyT** [comment]
rm(list=ls())
set.seed(1234)
library(missSBM)
data("FrenchPolBlog", package = "missSBM")

## Inference Full graph : ##
vBlocks <- 1:15 # number of classes

sbm_full <-
  missSBM(
    FrenchPolBlog,
    vBlocks,
    "dyad",
    clusterInit = "spectral",
    smoothing = "forward",
    iter_both = 1,
    mc.cores = 6
  )

## Sampling of the data : ##

samplingParameters_NMAR <- runif(10)
sampledNet_NMAR <-
  sampleNetwork(
    FrenchPolBlog,
    "block-node",
    samplingParameters_NMAR,
    clusters = getBestModel(sbm_full)$fittedSBM$memberships
  )

## Inference degree sampling : ##

sbm_forward_NMAR2 <- missSBM(sampledNet_NMAR$adjMatrix, vBlocks,"degree", clusterInit = "spectral", smoothing = "forward", iter_both = 1, mc.cores = 6)

**Comment by jchiquet** [comment]
With the last version of the package, the following piece of code works for me:

```r
set.seed(1234)
library(missSBM)
library(igraph)
data("frenchblog2007")

vBlocks <- 1:15 # number of classes
A <- frenchblog2007 %>% as_adj(sparse = FALSE)

sbm_full <- estimate(A, vBlocks, "dyad", clusterInit = "spectral", cores = 5)
plot(sbm_full$ICL)
smooth(sbm_full, "forward", cores = 5)
plot(sbm_full$ICL)

sbm_degree <- estimate(A, vBlocks, "degree", clusterInit = "spectral", cores = 5)
plot(sbm_degree$ICL)
smooth(sbm_degree, "forward", cores = 5)
plot(sbm_degree$ICL)
```
