### ISSUE TITLE
Bug : Warnings smoothing

### ISSUE THREAD

**Issue by TabouyT** [jchiquet/missSBM#25]
There are recurrent warnings that appears during the smoothing of ICL curve with degree sampling :  "In log(1 - prob) : NaNs produced"

**Comment by jchiquet** [comment]
Ok, Thanks !

Please provide a minimal reproducible example.

**Comment by Demiperimetre** [comment]
on the branch networks example, in the rmd file you have an example of the bug when trying to fit SBM on the fully observed data

**Comment by jchiquet** [comment]
Ok, je peux reproduire cet exemple.

Au passage, dans la branch networksExamples, j'ai mis la vignette au bon endroit, renommé le jeu de données war et créé un rda approprié.
