### ISSUE TITLE
Symmetric adj matrices?

### ISSUE THREAD

**Issue by Demiperimetre** [jchiquet/missSBM#27]
If the adjacency matrix is symmetric, does missSBM use the symmetric version of the lik?

**Comment by jchiquet** [comment]
Hopefully it will... Any error/strange thing encountered?

**Comment by jchiquet** [comment]
FYI, there are some tests to compare blockmodels output to missSBM output there, but for the moment we are (I am) only testing against SBM_sym. I did not check out "directed" version:

https://github.com/jchiquet/missSBM/blob/b40d1a42bef64d0feffea619d8e5a927e305f667/tests/testthat/test-SBM-sbm-fit-without-covariate.R#L37-L74

**Comment by jchiquet** [comment]
cher @Demiperimetre , je crois que ce qui t'inquiète c'est ton exemple sur la guerre : je crois que c'est plutôt une question de lissage d'ICL que d'optimisation qui fait la différence entre blockmodels et missSBM.

blockmodels choisit 3 classes, missSBM 4 classes. Notre modèle à 3 classes semble être bloqué dans un minimum local, avec une estimation de la matrice pi très différente de blockmodels à 3 classes. En revanche, les modèles à 4 classes sont comparables il me semble.

**Comment by Demiperimetre** [comment]
thanks. I was comparing the ICL from the two packages, but it should depend whether you use -2 or not in the computation. I should add something in the help to emphasize this point. 
Still, blockmodels and missSBM do not agree on the number of clusters

**Comment by jchiquet** [comment]
> Still, blockmodels and missSBM do not agree on the number of clusters

Yep, so this is indeed an issue...
