### ISSUE TITLE
Bug: Smooth()

### ISSUE THREAD

**Issue by TabouyT** [jchiquet/missSBM#28]
## Error: netSampling %in% available_samplings is not TRUE

When compiling JSS paper with knitr.

**Comment by jchiquet** [comment]
Could you tell me which Rnw file are you talking about ? If I cannot reproduce this, I cannot assess it.

**Comment by TabouyT** [comment]
Le notre dans le répertoire Documents/JSS-paper

**Comment by jchiquet** [comment]
ok, j'avais pas vu qu'il y en avait deux. Je peux effacer paper-JSS-kntir.tex ?

**Comment by TabouyT** [comment]
je pense oui

**Comment by TabouyT** [comment]
Same problem with "block-node" sampling :
## Error: netSampling %in% available_samplings is not TRUE

Le jeu. 28 mars 2019 à 13:14, Julien Chiquet <notifications@github.com> a
écrit :
