### ISSUE TITLE
Covariates for network / node sampling

### ISSUE THREAD

**Issue by Demiperimetre** [jchiquet/missSBM#35]
see inst/covariates.R 
In the particular case of a node sampling when we want to provide a matrix for the covariate on dyad

**Comment by Demiperimetre** [comment]
i uploaded a possible solution but it may disturb a potential user

**Comment by Demiperimetre** [comment]
ça devrait passer en fait, je détaillerai dans la vignette

**Comment by Demiperimetre** [comment]
Different but nevertheless related. 

Add option in estimate to take into account or not the available covariate. 
Add option for sampling node-cov and dyad-cov

When covariates are considered in the SBM, break if sampling != node, dyad, node-cov or dyad-cov

**Comment by jchiquet** [comment]
@Demiperimetre Dis moi si tu es heureux avec la dernière version du package pour ce qui concerne les covariables.

**Comment by Demiperimetre** [comment]
a priori oui, je suis pour l'instant toujours bloqué sur la comparaison avec blockmodels

**Comment by jchiquet** [comment]
> a priori oui, je suis pour l'instant toujours bloqué sur la comparaison avec blockmodels

C'est-à-dire ? Je ne compte plus changer le smoothing. Manifestement il n'est pas possible de contenter @TabouyT sur l'exemple de la blogosphere et @Demiperimetre sur l'exemple des réseaux de guerre. Je trouve que les ICL lissées avec la borne variationnelle sont quand même assez moches. Je pars 2 semaines, ça vous laisse le temps de vous mettre d'accord.
