### ISSUE TITLE
SetModel does not work for the model with greatest index

### ISSUE THREAD

**Issue by vravigne** [jchiquet/missSBM#41]
Hi Julien ! 

using SBM and LBM functions we would like to explore storedModels using the setModel method. But setModel does not allow exploring the last model, the one with the highest Index value. Is it possible to correct for that? 

Also, I have a question about the storedModels method. Are they all here or are there more than that stored but not accessible through the method storedModels ?

Virginie and Benoit

**Comment by jchiquet** [comment]
Hi Virginie. This bug was related to [sbm](https://github.com/GrossSBM/sbm), not missSBM.

It should be fixed now, at least for version posterior to commit https://github.com/GrossSBM/sbm/commit/17980c3a5c406a50e736c8300a89eb05913fc64f
